### PR TITLE
handle cases where termbox size cannot be determined

### LINKED ISSUE #39: runtime error: makeslice: len out of range
When following the instructions in the [contrib/cluster-maxscale/README.md](/mariadb-corporation/replication-manager/blob/0.7/contrib/cluster-maxscale/README.md) file I get this error after all the other services have been started.
~~~
panic: runtime error: makeslice: len out of range
replication-manager_1  | 
replication-manager_1  | goroutine 1 [running]:
replication-manager_1  | panic(0x972cc0, 0xc820278d20)
replication-manager_1  | 	/usr/local/go/src/runtime/panic.go:481 +0x3e6
replication-manager_1  | main.glob.func10(0xcf9460, 0xc820084c80, 0x0, 0x5)
replication-manager_1  | 	/go/src/replication-manager/repmgr.go:220 +0x35e
replication-manager_1  | replication-manager/vendor/github.com/spf13/cobra.(*Command).execute(0xcf9460, 0xc820084b40, 0x5, 0x5, 0x0, 0x0)
replication-manager_1  | 	/go/src/replication-manager/vendor/github.com/spf13/cobra/command.go:565 +0x85a
replication-manager_1  | replication-manager/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xcf8860, 0xcf9460, 0x0, 0x0)
replication-manager_1  | 	/go/src/replication-manager/vendor/github.com/spf13/cobra/command.go:651 +0x55c
replication-manager_1  | replication-manager/vendor/github.com/spf13/cobra.(*Command).Execute(0xcf8860, 0x0, 0x0)
replication-manager_1  | 	/go/src/replication-manager/vendor/github.com/spf13/cobra/command.go:610 +0x2d
replication-manager_1  | main.main()
replication-manager_1  | 	/go/src/replication-manager/main.go:30 +0x27
~~~

~~~
$ docker-compose ps                                                                                                                                                                                         Name                               Command               State             Ports          
---------------------------------------------------------------------------------------------------------
clustermaxscale_agent1_1                replication-manager agent  ...   Up                               
clustermaxscale_agent2_1                replication-manager agent  ...   Up                               
clustermaxscale_agent3_1                replication-manager agent  ...   Up                               
clustermaxscale_mariadb1_1              docker-entrypoint.sh --log ...   Up       3306/tcp                
clustermaxscale_mariadb2_1              docker-entrypoint.sh --log ...   Up       3306/tcp                
clustermaxscale_mariadb3_1              docker-entrypoint.sh --log ...   Up       3306/tcp                
clustermaxscale_maxscale_1              /usr/bin/maxscale --nodaem ...   Up       0.0.0.0:32772->3306/tcp 
clustermaxscale_replication-manager_1   replication-manager monito ...   Exit 2     
~~~

Passing `--daemon=true` in the command serves as workarround.

### PR DESCRIPTION
**Pull request by hugochinchilla**
closes #39

### CODE REVIEW

**Comment by tanji** [comment]
Is it really needed? If you run without terminal, you should use the --daemon option.

**Comment by hugochinchilla** [comment]
@tanji this allows all services defined in the docker-compose.yml to start without problems, then you can attach to the monitor container and use it interactively.

Maybe not 100% needed, but still a nice to have as it makes testing more easy.

**Comment by tanji** [comment]
Dockerfile does not build:

```
Sending build context to Docker daemon 74.93 MB
Step 1 : FROM golang:1.6-alpine
 ---> c40da134e949
Step 2 : RUN echo "@testing http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
 ---> Running in 6c104a34d32d
Container command '/bin/sh' not found or does not exist.
```

**Comment by hugochinchilla** [comment]
I've updated this PR to include only the thing it was intended to add.

About the Dockerfile not building, it's strange, something has changed which is broking it, I will take a look a it in PR #42

**Pull request merged**
