### PR TITLE
use glide to install dependecies in Dockerfile

### LINKED ISSUE #37: Cannot build Dockerfile on 0.7 branch because of go shitty package manager
~~~
$ docker-compose up -d                                                                                                                                                                           
Building agent3
Step 1 : FROM golang:1.6-alpine
 ---> 6deacc16609c
Step 2 : RUN apk add --update git && rm -rf /var/cache/apk/*
 ---> Using cache
 ---> c0b0d13aed26
Step 3 : RUN mkdir -p /go/src/replication-manager
 ---> Using cache
 ---> b31b34b27264
Step 4 : WORKDIR /go/src/replication-manager
 ---> Using cache
 ---> 7c6e0df18245
Step 5 : COPY . /go/src/replication-manager
 ---> e9b10693323a
Removing intermediate container db9cbcebd446
Step 6 : RUN go get .
 ---> Running in 6f70e32db8ec
package github.com/mariadb-corporation/replication-manager/gtid: cannot find package "github.com/mariadb-corporation/replication-manager/gtid" in any of:
	/usr/local/go/src/github.com/mariadb-corporation/replication-manager/gtid (from $GOROOT)
	/go/src/github.com/mariadb-corporation/replication-manager/gtid (from $GOPATH)
ERROR: Service 'agent3' failed to build: The command '/bin/sh -c go get .' returned a non-zero code: 1

~~~

### PR DESCRIPTION
**Pull request by hugochinchilla**
closes #37

### CODE REVIEW

**Comment by hugochinchilla** [comment]
Any problem with this PR?

**Comment by tanji** [comment]
I haven't had time to review it yet, sorry. I will try to check it today.

**Comment by hugochinchilla** [comment]
@tanji, can you try to build it now?

make sure to pull the latest version of golang:1.6-alpine first:

~~~
docker pull golang:1.6-alpine
docker build --no-cache -t replication-manager .
~~~

It works fine for me.

**Comment by tanji** [comment]
We shouldn't have to vendor local deps, I'm trying to find out what's wrong with that.

**Comment by tanji** [comment]
Fixed in 22adc12

**Pull request closed without merging**
